democoffee/config/routes.rb
Democoffee::Application.routes.draw do

  resources :users do
    get :value, on: :member
    get :check, on: :member
  end

  resources :admins do
    get :notificate_user, on: :member
  end

  root :to => 'welcomes#index'

  

end

democoffee/app/models/user.rb
#!/bin/env ruby  
# encoding: utf-8 
class User < ActiveRecord::Base
  image_accessor :qr_code

  def queue_info
    "现在时间是：#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}"
  end

  def queuing_people_num
    User.where(status: true).count
  end

  def average_wait_time
    @users = User.where("status = ?", false)
    if @users != []
      t = 0
      @users.each do |user|
        t = user.updated_at - user.created_at
      end
      return t / @users.count
    end
    return 0
  end

  def send_notification_mail
    response = RestClient.post "https://sendcloud.sohu.com/webapi/mail.send.xml",
    :api_user => "postmaster@mothinlab.sendcloud.org",
    :api_key => "y0hgJWwB",
    :from => "mothinlab@sendcloud.com",
    :fromname => "MothinLab",
    :to => "#{self.email}",
    :subject => "排队提醒",
    :html => "<h2>已经要排到您了</h2><h4>请对此次排队作出评价：<a href=\"#{value(3)}\">满意 </a><a href=\"#{value(2)}\">还行 </a><a href=\"#{value(1)}\">不满意</a><img src=\"#{self.qr_code.jpg.url}\"> </h4>"
    return response
  end

  def value(level)
    "http://192.168.0.104:3000" + "/users/#{self.id}" + "/value?level=#{level}"
  end

end

democoffee/app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @users = User.where("status = ?", true) 
    @finish_users = User.where("status = ?", false) 
  end

  def notificate_user
    @user = User.find_by_id(params[:id])
    @user.send_notification_mail
    @user.status = false
    redirect_to :back if @user.save
  end

end

democoffee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

democoffee/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.where(email: params[:email], status: true).first_or_create(email: params[:email], status: true)
    # true means user is in queuing
    qr_code_img = RQRCode::QRCode.new("http://192.168.0.104:3000/users/#{@user.id}/check", :size => 5, :level => :h ).to_img
    @user.update_attribute :qr_code, qr_code_img.resize(200,200).to_string
  end

  def value
    @user = User.find(params[:id])
    @user.value_level = params[:level]
    @user.save
  end

  def check
    @user = User.find(params[:id])
    @user.status = false
    @user.save
    @u = User.where("status = ?", true).first
    @u.send_notification_mail if @u
  end

end

democoffee/app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
    
  end

end

democoffee/app/helpers/application_helper.rb
module ApplicationHelper
end

democoffee/app/views/admins/index.html.erb
<div class="row" style="padding:15px">
	<h1>Admin</h1>
	<table class="table table-striped span5">
		<tr>
			<th>用户ID</th>
			<th>邮箱</th>
			<th>状态</th>
			<th>满意度</th>
			<th>操作</th>
		</tr>
		<% for user in @users %>
		<tr class="info">
			<td><%= user.id %></td>
			<td><%= user.email %></td>
			<td>等待</td>
			<td></td>
			<td><%= link_to "提醒", notificate_user_admin_path(user.id), class: "btn" %></td>
		</tr>

		<% end %>

		<% for user in @finish_users %>
		<tr class="success">
			<td><%= user.id %></td>
			<td><%= user.email %></td>
			<td>完毕</td>
			<td><%= user.value_level %></td>
			<td><%= link_to "查看", notificate_user_admin_path(user.id), class: "btn" %></td>
		</tr>

		<% end %>

	</table>
</div>

democoffee/app/views/layouts/_header.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<ul class="nav pull-left">
					<li><h4><%= link_to "MothinLab", root_path %></h4></li>
					<li><%= link_to "联系" %></li>
					<li><%= link_to "关于" %></li>
					<li><%= link_to "后台管理", admins_path%></li>
				</ul>
			</nav>
		</div>
	</div>
</div>

democoffee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Democoffee</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="mycontainer">
		<%= yield %>
	</div>

</body>
</html>

democoffee/app/views/users/create.html.erb
<h1>请保留并出示二维码</h1>
<%= image_tag @user.qr_code.jpg.url %>

democoffee/app/views/users/value.html.erb
<h1>感谢您的投票</h1>

democoffee/app/views/welcomes/index.html.erb
<p><%= User.new.queue_info %></p>
<p>在您前面有：  	<%= User.new.queuing_people_num %>人</p>
<p>大约等待时间：	<%= User.new.average_wait_time.to_i/60 %>分钟</p>

<p>请输入邮箱</p>

<form action="/users" accept-charset="UTF-8" method="POST">
	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
	<input name="email" type="email">
	<br>
	<input class="btn" type="submit" value="确定">
</form>